application: feed-buster
version: 10
runtime: python
api_version: 1

handlers:
- url: /mediaInjection(.*)
  script: feed-buster.py

- url: /cache(.*)
  script: feed-buster.py
  
- url: .*
  script: feed-buster.py