application: feed-buster
version: 11
runtime: python
api_version: 1

handlers:
- url: /mediaInjection(.*)
  script: feed-buster.py

- url: /cache(.*)
  script: feed-buster.py

- url: .*
  static_files : index.html
  upload: index.html